
    alter table Category 
        drop constraint FK6DD211E2C2EBFBA;

    alter table Request 
        drop constraint FKA4878A6FFBD5FB26;

    alter table Request 
        drop constraint FKA4878A6F79C2D1DB;

    alter table Request 
        drop constraint FKA4878A6FC70BAE6;

    alter table advertisement 
        drop constraint FKF85DD205F969E424;

    alter table advertisement 
        drop constraint FKF85DD205EA7030E5;

    alter table advertisement 
        drop constraint FKF85DD205FBD5FB26;

    alter table advertisement 
        drop constraint FKF85DD20579C2D1DB;

    alter table advertisement 
        drop constraint FKF85DD205C70BAE6;

    alter table photoset 
        drop constraint FKB40C78F096F7792E;

    alter table photoset 
        drop constraint FKB40C78F05D8FA15F;

    drop table Category if exists;

    drop table Person if exists;

    drop table Photo if exists;

    drop table Request if exists;

    drop table Unit if exists;

    drop table advertisement if exists;

    drop table photoset if exists;

    create table Category (
        id integer generated by default as identity (start with 1),
        title varchar(255) not null,
        parent_id integer,
        primary key (id)
    );

    create table Person (
        id integer generated by default as identity (start with 1),
        email varchar(255) not null,
        name varchar(255) not null,
        phone varchar(255) not null,
        uid varchar(255),
        primary key (id)
    );

    create table Photo (
        id integer generated by default as identity (start with 1),
        height integer not null,
        image mediumblob not null,
        mimeType varchar(255),
        thumbnail mediumblob not null,
        title varchar(255),
        uid varchar(255) not null,
        width integer not null,
        primary key (id)
    );

    create table Request (
        id integer generated by default as identity (start with 1),
        created datetime not null,
        creatorUid varchar(255) not null,
        description varchar(255) not null,
        status integer not null,
        title varchar(255) not null,
        category_id integer not null,
        contact_id integer not null,
        unit_id integer not null,
        primary key (id),
        unique (contact_id)
    );

    create table Unit (
        id integer generated by default as identity (start with 1),
        name varchar(255),
        primary key (id)
    );

    create table advertisement (
        id integer generated by default as identity (start with 1),
        created datetime not null,
        creatorUid varchar(255) not null,
        description varchar(255) not null,
        pickupAddress varchar(255) not null,
        pickupConditions varchar(255),
        status integer not null,
        title varchar(255) not null,
        booker_id integer,
        category_id integer not null,
        contact_id integer not null,
        displayUnit_id integer not null,
        unit_id integer not null,
        primary key (id),
        unique (contact_id)
    );

    create table photoset (
        advertisement_id integer not null,
        photos_id integer not null,
        primary key (advertisement_id, photos_id)
    );

    alter table Category 
        add constraint FK6DD211E2C2EBFBA 
        foreign key (parent_id) 
        references Category;

    alter table Request 
        add constraint FKA4878A6FFBD5FB26 
        foreign key (unit_id) 
        references Unit;

    alter table Request 
        add constraint FKA4878A6F79C2D1DB 
        foreign key (contact_id) 
        references Person;

    alter table Request 
        add constraint FKA4878A6FC70BAE6 
        foreign key (category_id) 
        references Category;

    alter table advertisement 
        add constraint FKF85DD205F969E424 
        foreign key (displayUnit_id) 
        references Unit;

    alter table advertisement 
        add constraint FKF85DD205EA7030E5 
        foreign key (booker_id) 
        references Person;

    alter table advertisement 
        add constraint FKF85DD205FBD5FB26 
        foreign key (unit_id) 
        references Unit;

    alter table advertisement 
        add constraint FKF85DD20579C2D1DB 
        foreign key (contact_id) 
        references Person;

    alter table advertisement 
        add constraint FKF85DD205C70BAE6 
        foreign key (category_id) 
        references Category;

    alter table photoset 
        add constraint FKB40C78F096F7792E 
        foreign key (advertisement_id) 
        references advertisement;

    alter table photoset 
        add constraint FKB40C78F05D8FA15F 
        foreign key (photos_id) 
        references Photo;
