delete from category where parent_id is not null;
delete from category where parent_id is null;

Insert into category (ID,TITLE,PARENT_ID) values ('1','Möbler',null);
Insert into category (ID,TITLE,PARENT_ID) values ('120','Inredning',null);
Insert into category (ID,TITLE,PARENT_ID) values ('126','Kontorsmöbler',null);
Insert into category (ID,TITLE,PARENT_ID) values ('136','Elektronik och vitvaror',null);
Insert into category (ID,TITLE,PARENT_ID) values ('139','Övrigt',null);
Insert into category (ID,TITLE,PARENT_ID) values ('121','Konst och utsmyckning','120');
Insert into category (ID,TITLE,PARENT_ID) values ('122','Belysning','120');
Insert into category (ID,TITLE,PARENT_ID) values ('123','Rumsväxter','120');
Insert into category (ID,TITLE,PARENT_ID) values ('124','Mattor och textilier','120');
Insert into category (ID,TITLE,PARENT_ID) values ('138','Ljud och bild','136');
Insert into category (ID,TITLE,PARENT_ID) values ('127','Skrivbord och hurtsar','126');
Insert into category (ID,TITLE,PARENT_ID) values ('128','Kontorsstolar','126');
Insert into category (ID,TITLE,PARENT_ID) values ('129','Hyllor och förvaring','126');
Insert into category (ID,TITLE,PARENT_ID) values ('130','Konferensmöbler','126');
Insert into category (ID,TITLE,PARENT_ID) values ('131','Soffor och fåtöljer','1');
Insert into category (ID,TITLE,PARENT_ID) values ('132','Bord och stolar','1');
Insert into category (ID,TITLE,PARENT_ID) values ('133','Förskola och skola','1');
Insert into category (ID,TITLE,PARENT_ID) values ('134','Hela möblemang','1');
Insert into category (ID,TITLE,PARENT_ID) values ('135','Källsorteringsutrustning','120');
Insert into category (ID,TITLE,PARENT_ID) values ('137','Vitvaror och köksmaskiner','136');
Insert into category (ID,TITLE,PARENT_ID) values ('140','Lekutrustning och leksaker','139');
Insert into category (ID,TITLE,PARENT_ID) values ('141','Verktyg','139');
Insert into category (ID,TITLE,PARENT_ID) values ('142','Husgeråd','139');
Insert into category (ID,TITLE,PARENT_ID) values ('143','Stöldskyddsutrustning','139');
Insert into category (ID,TITLE,PARENT_ID) values ('144','Övrigt','136');
Insert into category (ID,TITLE,PARENT_ID) values ('145','Övrigt','120');
Insert into category (ID,TITLE,PARENT_ID) values ('146','Övrigt','126');
Insert into category (ID,TITLE,PARENT_ID) values ('147','Övrigt','1');
Insert into category (ID,TITLE,PARENT_ID) values ('148','Övrigt','139');

delete from unit where id != '0';

Insert into unit (ID,NAME) values ('14','Angered');
Insert into unit (ID,NAME) values ('15','Askim-Frölunda-Högsbo');
Insert into unit (ID,NAME) values ('16','Centrum');
Insert into unit (ID,NAME) values ('17','Lundby');
Insert into unit (ID,NAME) values ('18','Majorna-Linné');
Insert into unit (ID,NAME) values ('19','Norra Hisingen');
Insert into unit (ID,NAME) values ('21','Västra Göteborg');
Insert into unit (ID,NAME) values ('22','Västra Hisingen');
Insert into unit (ID,NAME) values ('23','Örgryte-Härlanda');
Insert into unit (ID,NAME) values ('24','Östra Göteborg');
Insert into unit (ID,NAME) values ('101','Konsument- och medborgarservice');
Insert into unit (ID,NAME) values ('109','Kulturförvaltningen');
Insert into unit (ID,NAME) values ('103','Stadsbyggnadskontoret');
Insert into unit (ID,NAME) values ('104','Fastighetskontoret');
Insert into unit (ID,NAME) values ('116','Stadsrevisionen');
Insert into unit (ID,NAME) values ('106','Färdtjänstförvaltningen');
Insert into unit (ID,NAME) values ('107','Idrotts- och föreningsförvaltningen');
Insert into unit (ID,NAME) values ('108','Intraservice');
Insert into unit (ID,NAME) values ('110','Lokalförvaltningen');
Insert into unit (ID,NAME) values ('111','Miljöförvaltningen');
Insert into unit (ID,NAME) values ('112','Park- och naturförvaltningen');
Insert into unit (ID,NAME) values ('113','Regionarkivet');
Insert into unit (ID,NAME) values ('114','Social resursförvaltning');
Insert into unit (ID,NAME) values ('115','Stadsledningskontoret');
Insert into unit (ID,NAME) values ('117','Utbildningsförvaltningen');
Insert into unit (ID,NAME) values ('118','Vuxenutbildningsförvaltningen');
Insert into unit (ID,NAME) values ('119','Överförmyndarförvaltningen');
Insert into unit (ID,NAME) values ('85','Kretslopp och vatten');
Insert into unit (ID,NAME) values ('61','Trafikkontoret');
Insert into unit (ID,NAME) values ('16141','Poseidon');
Insert into unit (ID,NAME) values ('16142','Göteborgs Hamn');
Insert into unit (ID,NAME) values ('4044','Försäkrings AB Göta Lejon');
Insert into unit (ID,NAME) values ('5094','Göteborg & Co');
Insert into unit (ID,NAME) values ('15969','Gryaab AB');
Insert into unit (ID,NAME) values ('16095','Grefab');
Insert into unit (ID,NAME) values ('16176','Bostadsbolaget');
Insert into unit (ID,NAME) values ('16177','Familjebostäder');
Insert into unit (ID,NAME) values ('16178','Gårdstensbostäder');
Insert into unit (ID,NAME) values ('16179','Egnahemsbolaget');
Insert into unit (ID,NAME) values ('16180','Störningsjouren');
Insert into unit (ID,NAME) values ('16758','Göteborg Energi');
Insert into unit (ID,NAME) values ('17119','Stadsteatern');
Insert into unit (ID,NAME) values ('17141','Parkeringsbolaget');

commit;